<?php

/**
 * WorkflowApi
 * PHP version 7.2
 *
 * @category Class
 * @package  Libriciel\IparapheurV5\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * iparapheur
 *
 * iparapheur v5.x main core application.  The main link between every sub-services, integrating business code logic.
 *
 * The version of the OpenAPI document: DEVELOP
 * Contact: iparapheur@libriciel.coop
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Libriciel\IparapheurV5\Client\Api;

use GuzzleHttp\Psr7\MultipartStream;
use Http\Client\Common\Plugin\ErrorPlugin;
use Http\Client\Common\Plugin\RedirectPlugin;
use Http\Client\Common\PluginClient;
use Http\Client\Common\PluginClientFactory;
use Http\Client\Exception\HttpException;
use Http\Client\HttpAsyncClient;
use Http\Discovery\HttpAsyncClientDiscovery;
use Http\Discovery\Psr17FactoryDiscovery;
use Http\Discovery\Psr18ClientDiscovery;
use Http\Message\RequestFactory;
use Http\Promise\Promise;
use Libriciel\IparapheurV5\Client\ApiException;
use Libriciel\IparapheurV5\Client\Configuration;
use Libriciel\IparapheurV5\Client\DebugPlugin;
use Libriciel\IparapheurV5\Client\HeaderSelector;
use Libriciel\IparapheurV5\Client\FormDataProcessor;
use Libriciel\IparapheurV5\Client\ObjectSerializer;
use Psr\Http\Client\ClientExceptionInterface;
use Psr\Http\Client\ClientInterface;
use Psr\Http\Message\RequestFactoryInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\StreamFactoryInterface;
use Psr\Http\Message\UriFactoryInterface;
use Psr\Http\Message\UriInterface;
use function sprintf;

/**
 * WorkflowApi Class Doc Comment
 *
 * @category Class
 * @package  Libriciel\IparapheurV5\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WorkflowApi
{
    /**
     * @var PluginClient
     */
    protected $httpClient;

    /**
     * @var PluginClient
     */
    protected $httpAsyncClient;

    /**
     * @var UriFactoryInterface
     */
    protected $uriFactory;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @var RequestFactoryInterface
     */
    protected $requestFactory;

    /**
     * @var StreamFactoryInterface
     */
    protected $streamFactory;

    public function __construct(
        ?ClientInterface $httpClient = null,
        ?Configuration $config = null,
        ?HttpAsyncClient $httpAsyncClient = null,
        ?UriFactoryInterface $uriFactory = null,
        ?RequestFactoryInterface $requestFactory = null,
        ?StreamFactoryInterface $streamFactory = null,
        ?HeaderSelector $selector = null,
        ?array $plugins = null,
        $hostIndex = 0
    ) {
        $this->config = $config ?? (new Configuration())->setHost('http://localhost:8080');
        $this->requestFactory = $requestFactory ?? Psr17FactoryDiscovery::findRequestFactory();
        $this->streamFactory = $streamFactory ?? Psr17FactoryDiscovery::findStreamFactory();

        $plugins = $plugins ?? [
            new RedirectPlugin(['strict' => true]),
            new ErrorPlugin(),
        ];

        if ($this->config->getDebug()) {
            $plugins[] = new DebugPlugin(fopen($this->config->getDebugFile(), 'ab'));
        }

        $this->httpClient = (new PluginClientFactory())->createClient(
            $httpClient ?? Psr18ClientDiscovery::find(),
            $plugins
        );

        $this->httpAsyncClient = (new PluginClientFactory())->createClient(
            $httpAsyncClient ?? HttpAsyncClientDiscovery::find(),
            $plugins
        );

        $this->uriFactory = $uriFactory ?? Psr17FactoryDiscovery::findUriFactory();

        $this->headerSelector = $selector ?? new HeaderSelector();

        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation bypass
     *
     * Bypass
     *
     * @param  string $tenant_id Tenant id (required)
     * @param  string $desk_id Desk id (required)
     * @param  string $folder_id Folder id (required)
     * @param  string $task_id Task id (required)
     *
     * @throws \Libriciel\IparapheurV5\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function bypass($tenant_id, $desk_id, $folder_id, $task_id)
    {
        $this->bypassWithHttpInfo($tenant_id, $desk_id, $folder_id, $task_id);
    }

    /**
     * Operation bypassWithHttpInfo
     *
     * Bypass
     *
     * @param  string $tenant_id Tenant id (required)
     * @param  string $desk_id Desk id (required)
     * @param  string $folder_id Folder id (required)
     * @param  string $task_id Task id (required)
     *
     * @throws \Libriciel\IparapheurV5\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function bypassWithHttpInfo($tenant_id, $desk_id, $folder_id, $task_id)
    {
        $request = $this->bypassRequest($tenant_id, $desk_id, $folder_id, $task_id);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Libriciel\IparapheurV5\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Libriciel\IparapheurV5\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Libriciel\IparapheurV5\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Libriciel\IparapheurV5\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }


            throw $e;
        }
    }

    /**
     * Operation bypassAsync
     *
     * Bypass
     *
     * @param  string $tenant_id Tenant id (required)
     * @param  string $desk_id Desk id (required)
     * @param  string $folder_id Folder id (required)
     * @param  string $task_id Task id (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function bypassAsync($tenant_id, $desk_id, $folder_id, $task_id)
    {
        return $this->bypassAsyncWithHttpInfo($tenant_id, $desk_id, $folder_id, $task_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation bypassAsyncWithHttpInfo
     *
     * Bypass
     *
     * @param  string $tenant_id Tenant id (required)
     * @param  string $desk_id Desk id (required)
     * @param  string $folder_id Folder id (required)
     * @param  string $task_id Task id (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function bypassAsyncWithHttpInfo($tenant_id, $desk_id, $folder_id, $task_id)
    {
        $returnType = '';
        $request = $this->bypassRequest($tenant_id, $desk_id, $folder_id, $task_id);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'bypass'
     *
     * @param  string $tenant_id Tenant id (required)
     * @param  string $desk_id Desk id (required)
     * @param  string $folder_id Folder id (required)
     * @param  string $task_id Task id (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function bypassRequest($tenant_id, $desk_id, $folder_id, $task_id)
    {
        // verify the required parameter 'tenant_id' is set
        if ($tenant_id === null || (is_array($tenant_id) && count($tenant_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tenant_id when calling bypass'
            );
        }
        // verify the required parameter 'desk_id' is set
        if ($desk_id === null || (is_array($desk_id) && count($desk_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $desk_id when calling bypass'
            );
        }
        // verify the required parameter 'folder_id' is set
        if ($folder_id === null || (is_array($folder_id) && count($folder_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $folder_id when calling bypass'
            );
        }
        // verify the required parameter 'task_id' is set
        if ($task_id === null || (is_array($task_id) && count($task_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $task_id when calling bypass'
            );
        }

        $resourcePath = '/api/standard/v1/tenant/{tenantId}/desk/{deskId}/folder/{folderId}/task/{taskId}/bypass';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;



        // path params
        if ($tenant_id !== null) {
            $resourcePath = str_replace(
                '{' . 'tenantId' . '}',
                ObjectSerializer::toPathValue($tenant_id),
                $resourcePath
            );
        }
        // path params
        if ($desk_id !== null) {
            $resourcePath = str_replace(
                '{' . 'deskId' . '}',
                ObjectSerializer::toPathValue($desk_id),
                $resourcePath
            );
        }
        // path params
        if ($folder_id !== null) {
            $resourcePath = str_replace(
                '{' . 'folderId' . '}',
                ObjectSerializer::toPathValue($folder_id),
                $resourcePath
            );
        }
        // path params
        if ($task_id !== null) {
            $resourcePath = str_replace(
                '{' . 'taskId' . '}',
                ObjectSerializer::toPathValue($task_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('PUT', $uri, $headers, $httpBody);
    }

    /**
     * Operation seal
     *
     * Seal
     *
     * @param  string $tenant_id Tenant id (required)
     * @param  string $desk_id Desk id (required)
     * @param  string $folder_id Folder id (required)
     * @param  string $task_id Task id (required)
     * @param  \Libriciel\IparapheurV5\Client\Model\SealTaskParams $seal_task_params seal_task_params (required)
     *
     * @throws \Libriciel\IparapheurV5\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function seal($tenant_id, $desk_id, $folder_id, $task_id, $seal_task_params)
    {
        $this->sealWithHttpInfo($tenant_id, $desk_id, $folder_id, $task_id, $seal_task_params);
    }

    /**
     * Operation sealWithHttpInfo
     *
     * Seal
     *
     * @param  string $tenant_id Tenant id (required)
     * @param  string $desk_id Desk id (required)
     * @param  string $folder_id Folder id (required)
     * @param  string $task_id Task id (required)
     * @param  \Libriciel\IparapheurV5\Client\Model\SealTaskParams $seal_task_params (required)
     *
     * @throws \Libriciel\IparapheurV5\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function sealWithHttpInfo($tenant_id, $desk_id, $folder_id, $task_id, $seal_task_params)
    {
        $request = $this->sealRequest($tenant_id, $desk_id, $folder_id, $task_id, $seal_task_params);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Libriciel\IparapheurV5\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Libriciel\IparapheurV5\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Libriciel\IparapheurV5\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Libriciel\IparapheurV5\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }


            throw $e;
        }
    }

    /**
     * Operation sealAsync
     *
     * Seal
     *
     * @param  string $tenant_id Tenant id (required)
     * @param  string $desk_id Desk id (required)
     * @param  string $folder_id Folder id (required)
     * @param  string $task_id Task id (required)
     * @param  \Libriciel\IparapheurV5\Client\Model\SealTaskParams $seal_task_params (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function sealAsync($tenant_id, $desk_id, $folder_id, $task_id, $seal_task_params)
    {
        return $this->sealAsyncWithHttpInfo($tenant_id, $desk_id, $folder_id, $task_id, $seal_task_params)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sealAsyncWithHttpInfo
     *
     * Seal
     *
     * @param  string $tenant_id Tenant id (required)
     * @param  string $desk_id Desk id (required)
     * @param  string $folder_id Folder id (required)
     * @param  string $task_id Task id (required)
     * @param  \Libriciel\IparapheurV5\Client\Model\SealTaskParams $seal_task_params (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function sealAsyncWithHttpInfo($tenant_id, $desk_id, $folder_id, $task_id, $seal_task_params)
    {
        $returnType = '';
        $request = $this->sealRequest($tenant_id, $desk_id, $folder_id, $task_id, $seal_task_params);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'seal'
     *
     * @param  string $tenant_id Tenant id (required)
     * @param  string $desk_id Desk id (required)
     * @param  string $folder_id Folder id (required)
     * @param  string $task_id Task id (required)
     * @param  \Libriciel\IparapheurV5\Client\Model\SealTaskParams $seal_task_params (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function sealRequest($tenant_id, $desk_id, $folder_id, $task_id, $seal_task_params)
    {
        // verify the required parameter 'tenant_id' is set
        if ($tenant_id === null || (is_array($tenant_id) && count($tenant_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tenant_id when calling seal'
            );
        }
        // verify the required parameter 'desk_id' is set
        if ($desk_id === null || (is_array($desk_id) && count($desk_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $desk_id when calling seal'
            );
        }
        // verify the required parameter 'folder_id' is set
        if ($folder_id === null || (is_array($folder_id) && count($folder_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $folder_id when calling seal'
            );
        }
        // verify the required parameter 'task_id' is set
        if ($task_id === null || (is_array($task_id) && count($task_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $task_id when calling seal'
            );
        }
        // verify the required parameter 'seal_task_params' is set
        if ($seal_task_params === null || (is_array($seal_task_params) && count($seal_task_params) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $seal_task_params when calling seal'
            );
        }

        $resourcePath = '/api/standard/v1/tenant/{tenantId}/desk/{deskId}/folder/{folderId}/task/{taskId}/seal';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;



        // path params
        if ($tenant_id !== null) {
            $resourcePath = str_replace(
                '{' . 'tenantId' . '}',
                ObjectSerializer::toPathValue($tenant_id),
                $resourcePath
            );
        }
        // path params
        if ($desk_id !== null) {
            $resourcePath = str_replace(
                '{' . 'deskId' . '}',
                ObjectSerializer::toPathValue($desk_id),
                $resourcePath
            );
        }
        // path params
        if ($folder_id !== null) {
            $resourcePath = str_replace(
                '{' . 'folderId' . '}',
                ObjectSerializer::toPathValue($folder_id),
                $resourcePath
            );
        }
        // path params
        if ($task_id !== null) {
            $resourcePath = str_replace(
                '{' . 'taskId' . '}',
                ObjectSerializer::toPathValue($task_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (isset($seal_task_params)) {
            if ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($seal_task_params));
            } else {
                $httpBody = $seal_task_params;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('PUT', $uri, $headers, $httpBody);
    }

    /**
     * Operation secondOpinion
     *
     * Second opinion
     *
     * @param  string $tenant_id Tenant id (required)
     * @param  string $desk_id Desk id (required)
     * @param  string $folder_id Folder id (required)
     * @param  string $task_id Task id (required)
     * @param  \Libriciel\IparapheurV5\Client\Model\SimpleTaskParams $simple_task_params simple_task_params (required)
     *
     * @throws \Libriciel\IparapheurV5\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function secondOpinion($tenant_id, $desk_id, $folder_id, $task_id, $simple_task_params)
    {
        $this->secondOpinionWithHttpInfo($tenant_id, $desk_id, $folder_id, $task_id, $simple_task_params);
    }

    /**
     * Operation secondOpinionWithHttpInfo
     *
     * Second opinion
     *
     * @param  string $tenant_id Tenant id (required)
     * @param  string $desk_id Desk id (required)
     * @param  string $folder_id Folder id (required)
     * @param  string $task_id Task id (required)
     * @param  \Libriciel\IparapheurV5\Client\Model\SimpleTaskParams $simple_task_params (required)
     *
     * @throws \Libriciel\IparapheurV5\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function secondOpinionWithHttpInfo($tenant_id, $desk_id, $folder_id, $task_id, $simple_task_params)
    {
        $request = $this->secondOpinionRequest($tenant_id, $desk_id, $folder_id, $task_id, $simple_task_params);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Libriciel\IparapheurV5\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Libriciel\IparapheurV5\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Libriciel\IparapheurV5\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Libriciel\IparapheurV5\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }


            throw $e;
        }
    }

    /**
     * Operation secondOpinionAsync
     *
     * Second opinion
     *
     * @param  string $tenant_id Tenant id (required)
     * @param  string $desk_id Desk id (required)
     * @param  string $folder_id Folder id (required)
     * @param  string $task_id Task id (required)
     * @param  \Libriciel\IparapheurV5\Client\Model\SimpleTaskParams $simple_task_params (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function secondOpinionAsync($tenant_id, $desk_id, $folder_id, $task_id, $simple_task_params)
    {
        return $this->secondOpinionAsyncWithHttpInfo($tenant_id, $desk_id, $folder_id, $task_id, $simple_task_params)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation secondOpinionAsyncWithHttpInfo
     *
     * Second opinion
     *
     * @param  string $tenant_id Tenant id (required)
     * @param  string $desk_id Desk id (required)
     * @param  string $folder_id Folder id (required)
     * @param  string $task_id Task id (required)
     * @param  \Libriciel\IparapheurV5\Client\Model\SimpleTaskParams $simple_task_params (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function secondOpinionAsyncWithHttpInfo($tenant_id, $desk_id, $folder_id, $task_id, $simple_task_params)
    {
        $returnType = '';
        $request = $this->secondOpinionRequest($tenant_id, $desk_id, $folder_id, $task_id, $simple_task_params);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'secondOpinion'
     *
     * @param  string $tenant_id Tenant id (required)
     * @param  string $desk_id Desk id (required)
     * @param  string $folder_id Folder id (required)
     * @param  string $task_id Task id (required)
     * @param  \Libriciel\IparapheurV5\Client\Model\SimpleTaskParams $simple_task_params (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function secondOpinionRequest($tenant_id, $desk_id, $folder_id, $task_id, $simple_task_params)
    {
        // verify the required parameter 'tenant_id' is set
        if ($tenant_id === null || (is_array($tenant_id) && count($tenant_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tenant_id when calling secondOpinion'
            );
        }
        // verify the required parameter 'desk_id' is set
        if ($desk_id === null || (is_array($desk_id) && count($desk_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $desk_id when calling secondOpinion'
            );
        }
        // verify the required parameter 'folder_id' is set
        if ($folder_id === null || (is_array($folder_id) && count($folder_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $folder_id when calling secondOpinion'
            );
        }
        // verify the required parameter 'task_id' is set
        if ($task_id === null || (is_array($task_id) && count($task_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $task_id when calling secondOpinion'
            );
        }
        // verify the required parameter 'simple_task_params' is set
        if ($simple_task_params === null || (is_array($simple_task_params) && count($simple_task_params) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $simple_task_params when calling secondOpinion'
            );
        }

        $resourcePath = '/api/standard/v1/tenant/{tenantId}/desk/{deskId}/folder/{folderId}/task/{taskId}/second_opinion';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;



        // path params
        if ($tenant_id !== null) {
            $resourcePath = str_replace(
                '{' . 'tenantId' . '}',
                ObjectSerializer::toPathValue($tenant_id),
                $resourcePath
            );
        }
        // path params
        if ($desk_id !== null) {
            $resourcePath = str_replace(
                '{' . 'deskId' . '}',
                ObjectSerializer::toPathValue($desk_id),
                $resourcePath
            );
        }
        // path params
        if ($folder_id !== null) {
            $resourcePath = str_replace(
                '{' . 'folderId' . '}',
                ObjectSerializer::toPathValue($folder_id),
                $resourcePath
            );
        }
        // path params
        if ($task_id !== null) {
            $resourcePath = str_replace(
                '{' . 'taskId' . '}',
                ObjectSerializer::toPathValue($task_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (isset($simple_task_params)) {
            if ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($simple_task_params));
            } else {
                $httpBody = $simple_task_params;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('PUT', $uri, $headers, $httpBody);
    }

    /**
     * Operation sendToTrashBin
     *
     * Send to trash-bin
     *
     * @param  string $tenant_id Tenant id (required)
     * @param  string $desk_id Desk id (required)
     * @param  string $folder_id Folder id (required)
     * @param  string $task_id task_id (required)
     *
     * @throws \Libriciel\IparapheurV5\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function sendToTrashBin($tenant_id, $desk_id, $folder_id, $task_id)
    {
        $this->sendToTrashBinWithHttpInfo($tenant_id, $desk_id, $folder_id, $task_id);
    }

    /**
     * Operation sendToTrashBinWithHttpInfo
     *
     * Send to trash-bin
     *
     * @param  string $tenant_id Tenant id (required)
     * @param  string $desk_id Desk id (required)
     * @param  string $folder_id Folder id (required)
     * @param  string $task_id (required)
     *
     * @throws \Libriciel\IparapheurV5\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function sendToTrashBinWithHttpInfo($tenant_id, $desk_id, $folder_id, $task_id)
    {
        $request = $this->sendToTrashBinRequest($tenant_id, $desk_id, $folder_id, $task_id);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Libriciel\IparapheurV5\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Libriciel\IparapheurV5\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Libriciel\IparapheurV5\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Libriciel\IparapheurV5\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }


            throw $e;
        }
    }

    /**
     * Operation sendToTrashBinAsync
     *
     * Send to trash-bin
     *
     * @param  string $tenant_id Tenant id (required)
     * @param  string $desk_id Desk id (required)
     * @param  string $folder_id Folder id (required)
     * @param  string $task_id (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function sendToTrashBinAsync($tenant_id, $desk_id, $folder_id, $task_id)
    {
        return $this->sendToTrashBinAsyncWithHttpInfo($tenant_id, $desk_id, $folder_id, $task_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sendToTrashBinAsyncWithHttpInfo
     *
     * Send to trash-bin
     *
     * @param  string $tenant_id Tenant id (required)
     * @param  string $desk_id Desk id (required)
     * @param  string $folder_id Folder id (required)
     * @param  string $task_id (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function sendToTrashBinAsyncWithHttpInfo($tenant_id, $desk_id, $folder_id, $task_id)
    {
        $returnType = '';
        $request = $this->sendToTrashBinRequest($tenant_id, $desk_id, $folder_id, $task_id);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'sendToTrashBin'
     *
     * @param  string $tenant_id Tenant id (required)
     * @param  string $desk_id Desk id (required)
     * @param  string $folder_id Folder id (required)
     * @param  string $task_id (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function sendToTrashBinRequest($tenant_id, $desk_id, $folder_id, $task_id)
    {
        // verify the required parameter 'tenant_id' is set
        if ($tenant_id === null || (is_array($tenant_id) && count($tenant_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tenant_id when calling sendToTrashBin'
            );
        }
        // verify the required parameter 'desk_id' is set
        if ($desk_id === null || (is_array($desk_id) && count($desk_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $desk_id when calling sendToTrashBin'
            );
        }
        // verify the required parameter 'folder_id' is set
        if ($folder_id === null || (is_array($folder_id) && count($folder_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $folder_id when calling sendToTrashBin'
            );
        }
        // verify the required parameter 'task_id' is set
        if ($task_id === null || (is_array($task_id) && count($task_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $task_id when calling sendToTrashBin'
            );
        }

        $resourcePath = '/api/standard/v1/tenant/{tenantId}/desk/{deskId}/folder/{folderId}/task/{taskId}/send_to_trash_bin';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;



        // path params
        if ($tenant_id !== null) {
            $resourcePath = str_replace(
                '{' . 'tenantId' . '}',
                ObjectSerializer::toPathValue($tenant_id),
                $resourcePath
            );
        }
        // path params
        if ($desk_id !== null) {
            $resourcePath = str_replace(
                '{' . 'deskId' . '}',
                ObjectSerializer::toPathValue($desk_id),
                $resourcePath
            );
        }
        // path params
        if ($folder_id !== null) {
            $resourcePath = str_replace(
                '{' . 'folderId' . '}',
                ObjectSerializer::toPathValue($folder_id),
                $resourcePath
            );
        }
        // path params
        if ($task_id !== null) {
            $resourcePath = str_replace(
                '{' . 'taskId' . '}',
                ObjectSerializer::toPathValue($task_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('PUT', $uri, $headers, $httpBody);
    }

    /**
     * Operation start
     *
     * Start
     *
     * @param  string $tenant_id Tenant id (required)
     * @param  string $desk_id Desk id (required)
     * @param  string $folder_id Folder id (required)
     * @param  string $task_id task_id (required)
     * @param  \Libriciel\IparapheurV5\Client\Model\SimpleTaskParams $simple_task_params simple_task_params (required)
     *
     * @throws \Libriciel\IparapheurV5\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function start($tenant_id, $desk_id, $folder_id, $task_id, $simple_task_params)
    {
        $this->startWithHttpInfo($tenant_id, $desk_id, $folder_id, $task_id, $simple_task_params);
    }

    /**
     * Operation startWithHttpInfo
     *
     * Start
     *
     * @param  string $tenant_id Tenant id (required)
     * @param  string $desk_id Desk id (required)
     * @param  string $folder_id Folder id (required)
     * @param  string $task_id (required)
     * @param  \Libriciel\IparapheurV5\Client\Model\SimpleTaskParams $simple_task_params (required)
     *
     * @throws \Libriciel\IparapheurV5\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function startWithHttpInfo($tenant_id, $desk_id, $folder_id, $task_id, $simple_task_params)
    {
        $request = $this->startRequest($tenant_id, $desk_id, $folder_id, $task_id, $simple_task_params);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Libriciel\IparapheurV5\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Libriciel\IparapheurV5\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Libriciel\IparapheurV5\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 407:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Libriciel\IparapheurV5\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }


            throw $e;
        }
    }

    /**
     * Operation startAsync
     *
     * Start
     *
     * @param  string $tenant_id Tenant id (required)
     * @param  string $desk_id Desk id (required)
     * @param  string $folder_id Folder id (required)
     * @param  string $task_id (required)
     * @param  \Libriciel\IparapheurV5\Client\Model\SimpleTaskParams $simple_task_params (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function startAsync($tenant_id, $desk_id, $folder_id, $task_id, $simple_task_params)
    {
        return $this->startAsyncWithHttpInfo($tenant_id, $desk_id, $folder_id, $task_id, $simple_task_params)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation startAsyncWithHttpInfo
     *
     * Start
     *
     * @param  string $tenant_id Tenant id (required)
     * @param  string $desk_id Desk id (required)
     * @param  string $folder_id Folder id (required)
     * @param  string $task_id (required)
     * @param  \Libriciel\IparapheurV5\Client\Model\SimpleTaskParams $simple_task_params (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function startAsyncWithHttpInfo($tenant_id, $desk_id, $folder_id, $task_id, $simple_task_params)
    {
        $returnType = '';
        $request = $this->startRequest($tenant_id, $desk_id, $folder_id, $task_id, $simple_task_params);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'start'
     *
     * @param  string $tenant_id Tenant id (required)
     * @param  string $desk_id Desk id (required)
     * @param  string $folder_id Folder id (required)
     * @param  string $task_id (required)
     * @param  \Libriciel\IparapheurV5\Client\Model\SimpleTaskParams $simple_task_params (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function startRequest($tenant_id, $desk_id, $folder_id, $task_id, $simple_task_params)
    {
        // verify the required parameter 'tenant_id' is set
        if ($tenant_id === null || (is_array($tenant_id) && count($tenant_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tenant_id when calling start'
            );
        }
        // verify the required parameter 'desk_id' is set
        if ($desk_id === null || (is_array($desk_id) && count($desk_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $desk_id when calling start'
            );
        }
        // verify the required parameter 'folder_id' is set
        if ($folder_id === null || (is_array($folder_id) && count($folder_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $folder_id when calling start'
            );
        }
        // verify the required parameter 'task_id' is set
        if ($task_id === null || (is_array($task_id) && count($task_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $task_id when calling start'
            );
        }
        // verify the required parameter 'simple_task_params' is set
        if ($simple_task_params === null || (is_array($simple_task_params) && count($simple_task_params) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $simple_task_params when calling start'
            );
        }

        $resourcePath = '/api/standard/v1/tenant/{tenantId}/desk/{deskId}/folder/{folderId}/task/{taskId}/start';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;



        // path params
        if ($tenant_id !== null) {
            $resourcePath = str_replace(
                '{' . 'tenantId' . '}',
                ObjectSerializer::toPathValue($tenant_id),
                $resourcePath
            );
        }
        // path params
        if ($desk_id !== null) {
            $resourcePath = str_replace(
                '{' . 'deskId' . '}',
                ObjectSerializer::toPathValue($desk_id),
                $resourcePath
            );
        }
        // path params
        if ($folder_id !== null) {
            $resourcePath = str_replace(
                '{' . 'folderId' . '}',
                ObjectSerializer::toPathValue($folder_id),
                $resourcePath
            );
        }
        // path params
        if ($task_id !== null) {
            $resourcePath = str_replace(
                '{' . 'taskId' . '}',
                ObjectSerializer::toPathValue($task_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (isset($simple_task_params)) {
            if ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($simple_task_params));
            } else {
                $httpBody = $simple_task_params;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('PUT', $uri, $headers, $httpBody);
    }

    /**
     * Operation undo
     *
     * Undo
     *
     * @param  string $tenant_id Tenant id (required)
     * @param  string $desk_id Desk id (required)
     * @param  string $folder_id Folder id (required)
     * @param  string $task_id Task id (required)
     *
     * @throws \Libriciel\IparapheurV5\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function undo($tenant_id, $desk_id, $folder_id, $task_id)
    {
        $this->undoWithHttpInfo($tenant_id, $desk_id, $folder_id, $task_id);
    }

    /**
     * Operation undoWithHttpInfo
     *
     * Undo
     *
     * @param  string $tenant_id Tenant id (required)
     * @param  string $desk_id Desk id (required)
     * @param  string $folder_id Folder id (required)
     * @param  string $task_id Task id (required)
     *
     * @throws \Libriciel\IparapheurV5\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function undoWithHttpInfo($tenant_id, $desk_id, $folder_id, $task_id)
    {
        $request = $this->undoRequest($tenant_id, $desk_id, $folder_id, $task_id);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Libriciel\IparapheurV5\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Libriciel\IparapheurV5\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Libriciel\IparapheurV5\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Libriciel\IparapheurV5\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }


            throw $e;
        }
    }

    /**
     * Operation undoAsync
     *
     * Undo
     *
     * @param  string $tenant_id Tenant id (required)
     * @param  string $desk_id Desk id (required)
     * @param  string $folder_id Folder id (required)
     * @param  string $task_id Task id (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function undoAsync($tenant_id, $desk_id, $folder_id, $task_id)
    {
        return $this->undoAsyncWithHttpInfo($tenant_id, $desk_id, $folder_id, $task_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation undoAsyncWithHttpInfo
     *
     * Undo
     *
     * @param  string $tenant_id Tenant id (required)
     * @param  string $desk_id Desk id (required)
     * @param  string $folder_id Folder id (required)
     * @param  string $task_id Task id (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function undoAsyncWithHttpInfo($tenant_id, $desk_id, $folder_id, $task_id)
    {
        $returnType = '';
        $request = $this->undoRequest($tenant_id, $desk_id, $folder_id, $task_id);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'undo'
     *
     * @param  string $tenant_id Tenant id (required)
     * @param  string $desk_id Desk id (required)
     * @param  string $folder_id Folder id (required)
     * @param  string $task_id Task id (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function undoRequest($tenant_id, $desk_id, $folder_id, $task_id)
    {
        // verify the required parameter 'tenant_id' is set
        if ($tenant_id === null || (is_array($tenant_id) && count($tenant_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tenant_id when calling undo'
            );
        }
        // verify the required parameter 'desk_id' is set
        if ($desk_id === null || (is_array($desk_id) && count($desk_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $desk_id when calling undo'
            );
        }
        // verify the required parameter 'folder_id' is set
        if ($folder_id === null || (is_array($folder_id) && count($folder_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $folder_id when calling undo'
            );
        }
        // verify the required parameter 'task_id' is set
        if ($task_id === null || (is_array($task_id) && count($task_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $task_id when calling undo'
            );
        }

        $resourcePath = '/api/standard/v1/tenant/{tenantId}/desk/{deskId}/folder/{folderId}/task/{taskId}/undo';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;



        // path params
        if ($tenant_id !== null) {
            $resourcePath = str_replace(
                '{' . 'tenantId' . '}',
                ObjectSerializer::toPathValue($tenant_id),
                $resourcePath
            );
        }
        // path params
        if ($desk_id !== null) {
            $resourcePath = str_replace(
                '{' . 'deskId' . '}',
                ObjectSerializer::toPathValue($desk_id),
                $resourcePath
            );
        }
        // path params
        if ($folder_id !== null) {
            $resourcePath = str_replace(
                '{' . 'folderId' . '}',
                ObjectSerializer::toPathValue($folder_id),
                $resourcePath
            );
        }
        // path params
        if ($task_id !== null) {
            $resourcePath = str_replace(
                '{' . 'taskId' . '}',
                ObjectSerializer::toPathValue($task_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('PUT', $uri, $headers, $httpBody);
    }

    /**
     * Operation visa
     *
     * Visa
     *
     * @param  string $tenant_id Tenant id (required)
     * @param  string $desk_id Desk id (required)
     * @param  string $folder_id Folder id (required)
     * @param  string $task_id Task id (required)
     * @param  \Libriciel\IparapheurV5\Client\Model\SimpleTaskParams $simple_task_params simple_task_params (required)
     *
     * @throws \Libriciel\IparapheurV5\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function visa($tenant_id, $desk_id, $folder_id, $task_id, $simple_task_params)
    {
        $this->visaWithHttpInfo($tenant_id, $desk_id, $folder_id, $task_id, $simple_task_params);
    }

    /**
     * Operation visaWithHttpInfo
     *
     * Visa
     *
     * @param  string $tenant_id Tenant id (required)
     * @param  string $desk_id Desk id (required)
     * @param  string $folder_id Folder id (required)
     * @param  string $task_id Task id (required)
     * @param  \Libriciel\IparapheurV5\Client\Model\SimpleTaskParams $simple_task_params (required)
     *
     * @throws \Libriciel\IparapheurV5\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function visaWithHttpInfo($tenant_id, $desk_id, $folder_id, $task_id, $simple_task_params)
    {
        $request = $this->visaRequest($tenant_id, $desk_id, $folder_id, $task_id, $simple_task_params);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Libriciel\IparapheurV5\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Libriciel\IparapheurV5\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Libriciel\IparapheurV5\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Libriciel\IparapheurV5\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }


            throw $e;
        }
    }

    /**
     * Operation visaAsync
     *
     * Visa
     *
     * @param  string $tenant_id Tenant id (required)
     * @param  string $desk_id Desk id (required)
     * @param  string $folder_id Folder id (required)
     * @param  string $task_id Task id (required)
     * @param  \Libriciel\IparapheurV5\Client\Model\SimpleTaskParams $simple_task_params (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function visaAsync($tenant_id, $desk_id, $folder_id, $task_id, $simple_task_params)
    {
        return $this->visaAsyncWithHttpInfo($tenant_id, $desk_id, $folder_id, $task_id, $simple_task_params)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation visaAsyncWithHttpInfo
     *
     * Visa
     *
     * @param  string $tenant_id Tenant id (required)
     * @param  string $desk_id Desk id (required)
     * @param  string $folder_id Folder id (required)
     * @param  string $task_id Task id (required)
     * @param  \Libriciel\IparapheurV5\Client\Model\SimpleTaskParams $simple_task_params (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function visaAsyncWithHttpInfo($tenant_id, $desk_id, $folder_id, $task_id, $simple_task_params)
    {
        $returnType = '';
        $request = $this->visaRequest($tenant_id, $desk_id, $folder_id, $task_id, $simple_task_params);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'visa'
     *
     * @param  string $tenant_id Tenant id (required)
     * @param  string $desk_id Desk id (required)
     * @param  string $folder_id Folder id (required)
     * @param  string $task_id Task id (required)
     * @param  \Libriciel\IparapheurV5\Client\Model\SimpleTaskParams $simple_task_params (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function visaRequest($tenant_id, $desk_id, $folder_id, $task_id, $simple_task_params)
    {
        // verify the required parameter 'tenant_id' is set
        if ($tenant_id === null || (is_array($tenant_id) && count($tenant_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tenant_id when calling visa'
            );
        }
        // verify the required parameter 'desk_id' is set
        if ($desk_id === null || (is_array($desk_id) && count($desk_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $desk_id when calling visa'
            );
        }
        // verify the required parameter 'folder_id' is set
        if ($folder_id === null || (is_array($folder_id) && count($folder_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $folder_id when calling visa'
            );
        }
        // verify the required parameter 'task_id' is set
        if ($task_id === null || (is_array($task_id) && count($task_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $task_id when calling visa'
            );
        }
        // verify the required parameter 'simple_task_params' is set
        if ($simple_task_params === null || (is_array($simple_task_params) && count($simple_task_params) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $simple_task_params when calling visa'
            );
        }

        $resourcePath = '/api/standard/v1/tenant/{tenantId}/desk/{deskId}/folder/{folderId}/task/{taskId}/visa';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;



        // path params
        if ($tenant_id !== null) {
            $resourcePath = str_replace(
                '{' . 'tenantId' . '}',
                ObjectSerializer::toPathValue($tenant_id),
                $resourcePath
            );
        }
        // path params
        if ($desk_id !== null) {
            $resourcePath = str_replace(
                '{' . 'deskId' . '}',
                ObjectSerializer::toPathValue($desk_id),
                $resourcePath
            );
        }
        // path params
        if ($folder_id !== null) {
            $resourcePath = str_replace(
                '{' . 'folderId' . '}',
                ObjectSerializer::toPathValue($folder_id),
                $resourcePath
            );
        }
        // path params
        if ($task_id !== null) {
            $resourcePath = str_replace(
                '{' . 'taskId' . '}',
                ObjectSerializer::toPathValue($task_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (isset($simple_task_params)) {
            if ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($simple_task_params));
            } else {
                $httpBody = $simple_task_params;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('PUT', $uri, $headers, $httpBody);
    }


    /**
     * @param string $method
     * @param string|UriInterface $uri
     * @param array $headers
     * @param string|StreamInterface|null $body
     *
     * @return RequestInterface
     */
    protected function createRequest(string $method, $uri, array $headers = [], $body = null): RequestInterface
    {
        if ($this->requestFactory instanceof RequestFactory) {
            return $this->requestFactory->createRequest(
                $method,
                $uri,
                $headers,
                $body
            );
        }

        if (is_string($body) && '' !== $body && null === $this->streamFactory) {
            throw new \RuntimeException('Cannot create request: A stream factory is required to create a request with a non-empty string body.');
        }

        $request = $this->requestFactory->createRequest($method, $uri);

        foreach ($headers as $key => $value) {
            $request = $request->withHeader($key, $value);
        }

        if (null !== $body && '' !== $body) {
            $request = $request->withBody(
                is_string($body) ? $this->streamFactory->createStream($body) : $body
            );
        }

        return $request;
    }

    private function createUri(
        string $operationHost,
        string $resourcePath,
        array $queryParams
    ): UriInterface {
        $parsedUrl = parse_url($operationHost);

        $host = $parsedUrl['host'] ?? null;
        $scheme = $parsedUrl['scheme'] ?? null;
        $basePath = $parsedUrl['path'] ?? null;
        $port = $parsedUrl['port'] ?? null;
        $user = $parsedUrl['user'] ?? null;
        $password = $parsedUrl['pass'] ?? null;

        $uri = $this->uriFactory->createUri($basePath . $resourcePath)
            ->withHost($host)
            ->withScheme($scheme)
            ->withPort($port)
            ->withQuery(ObjectSerializer::buildQuery($queryParams));

        if ($user) {
            $uri = $uri->withUserInfo($user, $password);
        }

        return $uri;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0] . '00');
        $right = (int) ($rangeCode[0] . '99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
