stages:
  - build
  - coding-standards
  - test
  - quality

variables:
  CONTAINER_IMAGE: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}"

build:
  stage: build
  tags:
    - docker-build
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build --pull -t "$CONTAINER_IMAGE" .
    - docker push "$CONTAINER_IMAGE"

lint:
  stage: coding-standards
  image: "$CONTAINER_IMAGE"
  script:
    - cd /app
    - vendor/bin/php-cs-fixer fix --dry-run --diff --allow-risky=yes

phpstan:
  stage: coding-standards
  image: "$CONTAINER_IMAGE"
  script:
    - cd /app
    - vendor/bin/phpstan

test:
  stage: test
  image: "$CONTAINER_IMAGE"
  variables:
    XDEBUG_MODE: coverage
  script:
    - cd /app
    - vendor/bin/phpunit --coverage-text

quality:
  stage: quality
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner -Dsonar.login=$SONAR_LOGIN -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.qualitygate.wait=true
  allow_failure: true
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
