# Required metadata
sonar.projectKey=iparapheur-v5-api-php
sonar.projectName=iparapheur v5 API client
sonar.projectVersion=master

# Project paths
sonar.sources=.
sonar.projectBaseDir=.
sonar.exclusions=vendor/**

# Exclude tests from the coverage
sonar.coverage.exclusions=tests/**

# Encoding of the source files
sonar.sourceEncoding=UTF-8
