<?php

namespace IparapheurV5Client\Model;

enum InternalMetadata: string
{
    case FOLDER_NAME = 'FOLDER_NAME';
    case FOLDER_TYPE = 'FOLDER_TYPE';
    case FOLDER_SUBTYPE = 'FOLDER_SUBTYPE';
    case LAST_VISA_DESK = 'LAST_VISA_DESK';
    case LAST_VISA_USER = 'LAST_VISA_USER';
    case LAST_VISA_DATE = 'LAST_VISA_DATE';
    case LAST_SIGNATURE_DESK = 'LAST_SIGNATURE_DESK';
    case LAST_SIGNATURE_USER = 'LAST_SIGNATURE_USER';
    case LAST_SIGNATURE_DATE = 'LAST_SIGNATURE_DATE';
    case LAST_SIGNATURE_DELEGATED_BY = 'LAST_SIGNATURE_DELEGATED_BY';
    case LAST_SIGNATURE_HASH = 'LAST_SIGNATURE_HASH';
}
