<?php

/**
 * Action
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Libriciel\IparapheurV5\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * iparapheur
 *
 * iparapheur v5.x main core application.  The main link between every sub-services, integrating business code logic.
 *
 * The version of the OpenAPI document: DEVELOP
 * Contact: iparapheur@libriciel.coop
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Libriciel\IparapheurV5\Client\Model;
use Libriciel\IparapheurV5\Client\ObjectSerializer;

/**
 * Action Class Doc Comment
 *
 * @category Class
 * @package  Libriciel\IparapheurV5\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Action
{
    /**
     * Possible values of this enum
     */
    public const VISA = 'VISA';

    public const SEAL = 'SEAL';

    public const SIGNATURE = 'SIGNATURE';

    public const PAPER_SIGNATURE = 'PAPER_SIGNATURE';

    public const REJECT = 'REJECT';

    public const EXTERNAL_SIGNATURE = 'EXTERNAL_SIGNATURE';

    public const SECURE_MAIL = 'SECURE_MAIL';

    public const IPNG = 'IPNG';

    public const IPNG_RETURN = 'IPNG_RETURN';

    public const UNDO = 'UNDO';

    public const TRANSFER = 'TRANSFER';

    public const SECOND_OPINION = 'SECOND_OPINION';

    public const ASK_SECOND_OPINION = 'ASK_SECOND_OPINION';

    public const CREATE = 'CREATE';

    public const START = 'START';

    public const ARCHIVE = 'ARCHIVE';

    public const CHAIN = 'CHAIN';

    public const RECYCLE = 'RECYCLE';

    public const DELETE = 'DELETE';

    public const BYPASS = 'BYPASS';

    public const UPDATE = 'UPDATE';

    public const READ = 'READ';

    public const UNKNOWN = 'UNKNOWN';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::VISA,
            self::SEAL,
            self::SIGNATURE,
            self::PAPER_SIGNATURE,
            self::REJECT,
            self::EXTERNAL_SIGNATURE,
            self::SECURE_MAIL,
            self::IPNG,
            self::IPNG_RETURN,
            self::UNDO,
            self::TRANSFER,
            self::SECOND_OPINION,
            self::ASK_SECOND_OPINION,
            self::CREATE,
            self::START,
            self::ARCHIVE,
            self::CHAIN,
            self::RECYCLE,
            self::DELETE,
            self::BYPASS,
            self::UPDATE,
            self::READ,
            self::UNKNOWN
        ];
    }
}
