<?php

/**
 * FolderSortBy
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Libriciel\IparapheurV5\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * iparapheur
 *
 * iparapheur v5.x main core application.  The main link between every sub-services, integrating business code logic.
 *
 * The version of the OpenAPI document: DEVELOP
 * Contact: iparapheur@libriciel.coop
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Libriciel\IparapheurV5\Client\Model;
use Libriciel\IparapheurV5\Client\ObjectSerializer;

/**
 * FolderSortBy Class Doc Comment
 *
 * @category Class
 * @package  Libriciel\IparapheurV5\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FolderSortBy
{
    /**
     * Possible values of this enum
     */
    public const ACTION_TYPE = 'ACTION_TYPE';

    public const CREATION_DATE = 'CREATION_DATE';

    public const CURRENT_DESK_ID = 'CURRENT_DESK_ID';

    public const CURRENT_DESK_NAME = 'CURRENT_DESK_NAME';

    public const EMITTER_DESK_ID = 'EMITTER_DESK_ID';

    public const EMITTER_DESK_NAME = 'EMITTER_DESK_NAME';

    public const EMITTER_USER_ID = 'EMITTER_USER_ID';

    public const EMITTER_USER_NAME = 'EMITTER_USER_NAME';

    public const END_DATE = 'END_DATE';

    public const FOLDER_ID = 'FOLDER_ID';

    public const LEGACY_ID = 'LEGACY_ID';

    public const FOLDER_NAME = 'FOLDER_NAME';

    public const IS_READ = 'IS_READ';

    public const LATE_DATE = 'LATE_DATE';

    public const START_DATE = 'START_DATE';

    public const STILL_SINCE_DATE = 'STILL_SINCE_DATE';

    public const SUBTYPE_ID = 'SUBTYPE_ID';

    public const SUBTYPE_NAME = 'SUBTYPE_NAME';

    public const TASK_ID = 'TASK_ID';

    public const TYPE_ID = 'TYPE_ID';

    public const TYPE_NAME = 'TYPE_NAME';

    public const VALIDATION_START_DATE = 'VALIDATION_START_DATE';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ACTION_TYPE,
            self::CREATION_DATE,
            self::CURRENT_DESK_ID,
            self::CURRENT_DESK_NAME,
            self::EMITTER_DESK_ID,
            self::EMITTER_DESK_NAME,
            self::EMITTER_USER_ID,
            self::EMITTER_USER_NAME,
            self::END_DATE,
            self::FOLDER_ID,
            self::LEGACY_ID,
            self::FOLDER_NAME,
            self::IS_READ,
            self::LATE_DATE,
            self::START_DATE,
            self::STILL_SINCE_DATE,
            self::SUBTYPE_ID,
            self::SUBTYPE_NAME,
            self::TASK_ID,
            self::TYPE_ID,
            self::TYPE_NAME,
            self::VALIDATION_START_DATE
        ];
    }
}
