<?php
/**
 * FolderSortBy
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * iparapheur
 *
 * iparapheur v5.x main core application.  The main link between every sub-services, integrating business code logic.
 *
 * The version of the OpenAPI document: DEVELOP
 * Contact: iparapheur@libriciel.coop
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * FolderSortBy Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FolderSortBy
{
    /**
     * Possible values of this enum
     */
    public const VALIDATION_START_DATE = 'VALIDATION_START_DATE';

    public const CREATION_DATE = 'CREATION_DATE';

    public const STILL_SINCE_DATE = 'STILL_SINCE_DATE';

    public const LATE_DATE = 'LATE_DATE';

    public const END_DATE = 'END_DATE';

    public const TASK_ID = 'TASK_ID';

    public const FOLDER_ID = 'FOLDER_ID';

    public const FOLDER_NAME = 'FOLDER_NAME';

    public const TYPE_ID = 'TYPE_ID';

    public const TYPE_NAME = 'TYPE_NAME';

    public const SUBTYPE_ID = 'SUBTYPE_ID';

    public const SUBTYPE_NAME = 'SUBTYPE_NAME';

    public const ACTION_TYPE = 'ACTION_TYPE';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::VALIDATION_START_DATE,
            self::CREATION_DATE,
            self::STILL_SINCE_DATE,
            self::LATE_DATE,
            self::END_DATE,
            self::TASK_ID,
            self::FOLDER_ID,
            self::FOLDER_NAME,
            self::TYPE_ID,
            self::TYPE_NAME,
            self::SUBTYPE_ID,
            self::SUBTYPE_NAME,
            self::ACTION_TYPE
        ];
    }
}


