<?php

/**
 * MailParams
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Libriciel\IparapheurV5\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * iparapheur
 *
 * iparapheur v5.x main core application.  The main link between every sub-services, integrating business code logic.
 *
 * The version of the OpenAPI document: DEVELOP
 * Contact: iparapheur@libriciel.coop
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Libriciel\IparapheurV5\Client\Model;

use ArrayAccess;
use Libriciel\IparapheurV5\Client\ObjectSerializer;

/**
 * MailParams Class Doc Comment
 *
 * @category Class
 * @description body
 * @package  Libriciel\IparapheurV5\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MailParams implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'MailParams';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'public_annotation' => 'string',
        'private_annotation' => 'string',
        'metadata' => 'array<string,string>',
        'to' => 'string[]',
        'cc' => 'string[]',
        'bcc' => 'string[]',
        'object' => 'string',
        'message' => 'string',
        'password' => 'string',
        'payload' => 'string',
        'include_docket' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'public_annotation' => null,
        'private_annotation' => null,
        'metadata' => null,
        'to' => null,
        'cc' => null,
        'bcc' => null,
        'object' => null,
        'message' => null,
        'password' => null,
        'payload' => null,
        'include_docket' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'public_annotation' => false,
        'private_annotation' => false,
        'metadata' => true,
        'to' => false,
        'cc' => false,
        'bcc' => false,
        'object' => false,
        'message' => false,
        'password' => false,
        'payload' => false,
        'include_docket' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'public_annotation' => 'publicAnnotation',
        'private_annotation' => 'privateAnnotation',
        'metadata' => 'metadata',
        'to' => 'to',
        'cc' => 'cc',
        'bcc' => 'bcc',
        'object' => 'object',
        'message' => 'message',
        'password' => 'password',
        'payload' => 'payload',
        'include_docket' => 'includeDocket'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'public_annotation' => 'setPublicAnnotation',
        'private_annotation' => 'setPrivateAnnotation',
        'metadata' => 'setMetadata',
        'to' => 'setTo',
        'cc' => 'setCc',
        'bcc' => 'setBcc',
        'object' => 'setObject',
        'message' => 'setMessage',
        'password' => 'setPassword',
        'payload' => 'setPayload',
        'include_docket' => 'setIncludeDocket'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'public_annotation' => 'getPublicAnnotation',
        'private_annotation' => 'getPrivateAnnotation',
        'metadata' => 'getMetadata',
        'to' => 'getTo',
        'cc' => 'getCc',
        'bcc' => 'getBcc',
        'object' => 'getObject',
        'message' => 'getMessage',
        'password' => 'getPassword',
        'payload' => 'getPayload',
        'include_docket' => 'getIncludeDocket'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('public_annotation', $data ?? [], null);
        $this->setIfExists('private_annotation', $data ?? [], null);
        $this->setIfExists('metadata', $data ?? [], null);
        $this->setIfExists('to', $data ?? [], null);
        $this->setIfExists('cc', $data ?? [], null);
        $this->setIfExists('bcc', $data ?? [], null);
        $this->setIfExists('object', $data ?? [], null);
        $this->setIfExists('message', $data ?? [], null);
        $this->setIfExists('password', $data ?? [], null);
        $this->setIfExists('payload', $data ?? [], null);
        $this->setIfExists('include_docket', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['public_annotation']) && (mb_strlen($this->container['public_annotation']) > 512)) {
            $invalidProperties[] = "invalid value for 'public_annotation', the character length must be smaller than or equal to 512.";
        }

        if (!is_null($this->container['public_annotation']) && (mb_strlen($this->container['public_annotation']) < 0)) {
            $invalidProperties[] = "invalid value for 'public_annotation', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['private_annotation']) && (mb_strlen($this->container['private_annotation']) > 512)) {
            $invalidProperties[] = "invalid value for 'private_annotation', the character length must be smaller than or equal to 512.";
        }

        if (!is_null($this->container['private_annotation']) && (mb_strlen($this->container['private_annotation']) < 0)) {
            $invalidProperties[] = "invalid value for 'private_annotation', the character length must be bigger than or equal to 0.";
        }

        if ($this->container['to'] === null) {
            $invalidProperties[] = "'to' can't be null";
        }
        if ($this->container['object'] === null) {
            $invalidProperties[] = "'object' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets public_annotation
     *
     * @return string|null
     */
    public function getPublicAnnotation()
    {
        return $this->container['public_annotation'];
    }

    /**
     * Sets public_annotation
     *
     * @param string|null $public_annotation public_annotation
     *
     * @return self
     */
    public function setPublicAnnotation($public_annotation)
    {
        if (is_null($public_annotation)) {
            throw new \InvalidArgumentException('non-nullable public_annotation cannot be null');
        }
        if ((mb_strlen($public_annotation) > 512)) {
            throw new \InvalidArgumentException('invalid length for $public_annotation when calling MailParams., must be smaller than or equal to 512.');
        }
        if ((mb_strlen($public_annotation) < 0)) {
            throw new \InvalidArgumentException('invalid length for $public_annotation when calling MailParams., must be bigger than or equal to 0.');
        }

        $this->container['public_annotation'] = $public_annotation;

        return $this;
    }

    /**
     * Gets private_annotation
     *
     * @return string|null
     */
    public function getPrivateAnnotation()
    {
        return $this->container['private_annotation'];
    }

    /**
     * Sets private_annotation
     *
     * @param string|null $private_annotation private_annotation
     *
     * @return self
     */
    public function setPrivateAnnotation($private_annotation)
    {
        if (is_null($private_annotation)) {
            throw new \InvalidArgumentException('non-nullable private_annotation cannot be null');
        }
        if ((mb_strlen($private_annotation) > 512)) {
            throw new \InvalidArgumentException('invalid length for $private_annotation when calling MailParams., must be smaller than or equal to 512.');
        }
        if ((mb_strlen($private_annotation) < 0)) {
            throw new \InvalidArgumentException('invalid length for $private_annotation when calling MailParams., must be bigger than or equal to 0.');
        }

        $this->container['private_annotation'] = $private_annotation;

        return $this;
    }

    /**
     * Gets metadata
     *
     * @return array<string,string>|null
     */
    public function getMetadata()
    {
        return $this->container['metadata'];
    }

    /**
     * Sets metadata
     *
     * @param array<string,string>|null $metadata metadata
     *
     * @return self
     */
    public function setMetadata($metadata)
    {
        if (is_null($metadata)) {
            array_push($this->openAPINullablesSetToNull, 'metadata');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('metadata', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['metadata'] = $metadata;

        return $this;
    }

    /**
     * Gets to
     *
     * @return string[]
     */
    public function getTo()
    {
        return $this->container['to'];
    }

    /**
     * Sets to
     *
     * @param string[] $to to
     *
     * @return self
     */
    public function setTo($to)
    {
        if (is_null($to)) {
            throw new \InvalidArgumentException('non-nullable to cannot be null');
        }
        $this->container['to'] = $to;

        return $this;
    }

    /**
     * Gets cc
     *
     * @return string[]|null
     */
    public function getCc()
    {
        return $this->container['cc'];
    }

    /**
     * Sets cc
     *
     * @param string[]|null $cc cc
     *
     * @return self
     */
    public function setCc($cc)
    {
        if (is_null($cc)) {
            throw new \InvalidArgumentException('non-nullable cc cannot be null');
        }
        $this->container['cc'] = $cc;

        return $this;
    }

    /**
     * Gets bcc
     *
     * @return string[]|null
     */
    public function getBcc()
    {
        return $this->container['bcc'];
    }

    /**
     * Sets bcc
     *
     * @param string[]|null $bcc bcc
     *
     * @return self
     */
    public function setBcc($bcc)
    {
        if (is_null($bcc)) {
            throw new \InvalidArgumentException('non-nullable bcc cannot be null');
        }
        $this->container['bcc'] = $bcc;

        return $this;
    }

    /**
     * Gets object
     *
     * @return string
     */
    public function getObject()
    {
        return $this->container['object'];
    }

    /**
     * Sets object
     *
     * @param string $object object
     *
     * @return self
     */
    public function setObject($object)
    {
        if (is_null($object)) {
            throw new \InvalidArgumentException('non-nullable object cannot be null');
        }
        $this->container['object'] = $object;

        return $this;
    }

    /**
     * Gets message
     *
     * @return string|null
     */
    public function getMessage()
    {
        return $this->container['message'];
    }

    /**
     * Sets message
     *
     * @param string|null $message message
     *
     * @return self
     */
    public function setMessage($message)
    {
        if (is_null($message)) {
            throw new \InvalidArgumentException('non-nullable message cannot be null');
        }
        $this->container['message'] = $message;

        return $this;
    }

    /**
     * Gets password
     *
     * @return string|null
     */
    public function getPassword()
    {
        return $this->container['password'];
    }

    /**
     * Sets password
     *
     * @param string|null $password password
     *
     * @return self
     */
    public function setPassword($password)
    {
        if (is_null($password)) {
            throw new \InvalidArgumentException('non-nullable password cannot be null');
        }
        $this->container['password'] = $password;

        return $this;
    }

    /**
     * Gets payload
     *
     * @return string|null
     */
    public function getPayload()
    {
        return $this->container['payload'];
    }

    /**
     * Sets payload
     *
     * @param string|null $payload payload
     *
     * @return self
     */
    public function setPayload($payload)
    {
        if (is_null($payload)) {
            throw new \InvalidArgumentException('non-nullable payload cannot be null');
        }
        $this->container['payload'] = $payload;

        return $this;
    }

    /**
     * Gets include_docket
     *
     * @return bool|null
     */
    public function getIncludeDocket()
    {
        return $this->container['include_docket'];
    }

    /**
     * Sets include_docket
     *
     * @param bool|null $include_docket include_docket
     *
     * @return self
     */
    public function setIncludeDocket($include_docket)
    {
        if (is_null($include_docket)) {
            throw new \InvalidArgumentException('non-nullable include_docket cannot be null');
        }
        $this->container['include_docket'] = $include_docket;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
