<?php

/**
 * SealTaskParams
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * iparapheur
 *
 * iparapheur v5.x main core application.  The main link between every sub-services, integrating business code logic.
 *
 * The version of the OpenAPI document: DEVELOP
 * Contact: iparapheur@libriciel.coop
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use ArrayAccess;
use OpenAPI\Client\ObjectSerializer;

/**
 * SealTaskParams Class Doc Comment
 *
 * @category Class
 * @description The public annotation is visible to any users, and will be stored in task history. It is mandatory for any reject, and should be longer than 3 characters.  The private annotation will only be sent to the workflow&#39;s next user. It won&#39;t be archived anywhere.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SealTaskParams implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SealTaskParams';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'public_annotation' => 'string',
        'private_annotation' => 'string',
        'metadata' => 'array<string,string>',
        'custom_signature_field' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'public_annotation' => null,
        'private_annotation' => null,
        'metadata' => null,
        'custom_signature_field' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'public_annotation' => false,
        'private_annotation' => false,
        'metadata' => true,
        'custom_signature_field' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'public_annotation' => 'publicAnnotation',
        'private_annotation' => 'privateAnnotation',
        'metadata' => 'metadata',
        'custom_signature_field' => 'customSignatureField'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'public_annotation' => 'setPublicAnnotation',
        'private_annotation' => 'setPrivateAnnotation',
        'metadata' => 'setMetadata',
        'custom_signature_field' => 'setCustomSignatureField'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'public_annotation' => 'getPublicAnnotation',
        'private_annotation' => 'getPrivateAnnotation',
        'metadata' => 'getMetadata',
        'custom_signature_field' => 'getCustomSignatureField'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('public_annotation', $data ?? [], null);
        $this->setIfExists('private_annotation', $data ?? [], null);
        $this->setIfExists('metadata', $data ?? [], null);
        $this->setIfExists('custom_signature_field', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['public_annotation']) && (mb_strlen($this->container['public_annotation']) > 512)) {
            $invalidProperties[] = "invalid value for 'public_annotation', the character length must be smaller than or equal to 512.";
        }

        if (!is_null($this->container['public_annotation']) && (mb_strlen($this->container['public_annotation']) < 0)) {
            $invalidProperties[] = "invalid value for 'public_annotation', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['private_annotation']) && (mb_strlen($this->container['private_annotation']) > 512)) {
            $invalidProperties[] = "invalid value for 'private_annotation', the character length must be smaller than or equal to 512.";
        }

        if (!is_null($this->container['private_annotation']) && (mb_strlen($this->container['private_annotation']) < 0)) {
            $invalidProperties[] = "invalid value for 'private_annotation', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['custom_signature_field']) && (mb_strlen($this->container['custom_signature_field']) > 512)) {
            $invalidProperties[] = "invalid value for 'custom_signature_field', the character length must be smaller than or equal to 512.";
        }

        if (!is_null($this->container['custom_signature_field']) && (mb_strlen($this->container['custom_signature_field']) < 0)) {
            $invalidProperties[] = "invalid value for 'custom_signature_field', the character length must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets public_annotation
     *
     * @return string|null
     */
    public function getPublicAnnotation()
    {
        return $this->container['public_annotation'];
    }

    /**
     * Sets public_annotation
     *
     * @param string|null $public_annotation public_annotation
     *
     * @return self
     */
    public function setPublicAnnotation($public_annotation)
    {
        if (is_null($public_annotation)) {
            throw new \InvalidArgumentException('non-nullable public_annotation cannot be null');
        }
        if ((mb_strlen($public_annotation) > 512)) {
            throw new \InvalidArgumentException('invalid length for $public_annotation when calling SealTaskParams., must be smaller than or equal to 512.');
        }
        if ((mb_strlen($public_annotation) < 0)) {
            throw new \InvalidArgumentException('invalid length for $public_annotation when calling SealTaskParams., must be bigger than or equal to 0.');
        }

        $this->container['public_annotation'] = $public_annotation;

        return $this;
    }

    /**
     * Gets private_annotation
     *
     * @return string|null
     */
    public function getPrivateAnnotation()
    {
        return $this->container['private_annotation'];
    }

    /**
     * Sets private_annotation
     *
     * @param string|null $private_annotation private_annotation
     *
     * @return self
     */
    public function setPrivateAnnotation($private_annotation)
    {
        if (is_null($private_annotation)) {
            throw new \InvalidArgumentException('non-nullable private_annotation cannot be null');
        }
        if ((mb_strlen($private_annotation) > 512)) {
            throw new \InvalidArgumentException('invalid length for $private_annotation when calling SealTaskParams., must be smaller than or equal to 512.');
        }
        if ((mb_strlen($private_annotation) < 0)) {
            throw new \InvalidArgumentException('invalid length for $private_annotation when calling SealTaskParams., must be bigger than or equal to 0.');
        }

        $this->container['private_annotation'] = $private_annotation;

        return $this;
    }

    /**
     * Gets metadata
     *
     * @return array<string,string>|null
     */
    public function getMetadata()
    {
        return $this->container['metadata'];
    }

    /**
     * Sets metadata
     *
     * @param array<string,string>|null $metadata metadata
     *
     * @return self
     */
    public function setMetadata($metadata)
    {
        if (is_null($metadata)) {
            array_push($this->openAPINullablesSetToNull, 'metadata');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('metadata', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['metadata'] = $metadata;

        return $this;
    }

    /**
     * Gets custom_signature_field
     *
     * @return string|null
     */
    public function getCustomSignatureField()
    {
        return $this->container['custom_signature_field'];
    }

    /**
     * Sets custom_signature_field
     *
     * @param string|null $custom_signature_field custom_signature_field
     *
     * @return self
     */
    public function setCustomSignatureField($custom_signature_field)
    {
        if (is_null($custom_signature_field)) {
            throw new \InvalidArgumentException('non-nullable custom_signature_field cannot be null');
        }
        if ((mb_strlen($custom_signature_field) > 512)) {
            throw new \InvalidArgumentException('invalid length for $custom_signature_field when calling SealTaskParams., must be smaller than or equal to 512.');
        }
        if ((mb_strlen($custom_signature_field) < 0)) {
            throw new \InvalidArgumentException('invalid length for $custom_signature_field when calling SealTaskParams., must be bigger than or equal to 0.');
        }

        $this->container['custom_signature_field'] = $custom_signature_field;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
