<?php
/**
 * State
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * iparapheur
 *
 * iparapheur v5.x main core application.  The main link between every sub-services, integrating business code logic.
 *
 * The version of the OpenAPI document: DEVELOP
 * Contact: iparapheur@libriciel.coop
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * State Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class State
{
    /**
     * Possible values of this enum
     */
    public const DRAFT = 'DRAFT';

    public const LATE = 'LATE';

    public const FINISHED = 'FINISHED';

    public const CURRENT = 'CURRENT';

    public const PENDING = 'PENDING';

    public const DELEGATED = 'DELEGATED';

    public const VALIDATED = 'VALIDATED';

    public const RETRIEVABLE = 'RETRIEVABLE';

    public const UPCOMING = 'UPCOMING';

    public const REJECTED = 'REJECTED';

    public const TRANSFERRED = 'TRANSFERRED';

    public const SECONDED = 'SECONDED';

    public const BYPASSED = 'BYPASSED';

    public const DOWNSTREAM = 'DOWNSTREAM';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DRAFT,
            self::LATE,
            self::FINISHED,
            self::CURRENT,
            self::PENDING,
            self::DELEGATED,
            self::VALIDATED,
            self::RETRIEVABLE,
            self::UPCOMING,
            self::REJECTED,
            self::TRANSFERRED,
            self::SECONDED,
            self::BYPASSED,
            self::DOWNSTREAM
        ];
    }
}


